In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

Digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, x_test, y_train, y_test = train_test_split(Digits.data,Digits.target,test_size=0.3)

In [3]:
# Disini menggunakan klasifikasi pertama, memakai Logisticregression
RR = LogisticRegression()
RR.fit(X_train, y_train)
RR.score(x_test, y_test)
# Mka hasil akurasinya 95%

D:\New folder\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9629629629629629

In [4]:
# Disini kita memakai SVM
svm = SVC()
svm.fit(X_train, y_train)
svm.score(x_test, y_test)

0.9925925925925926

In [5]:
# Lalu kita mencoba memakai Random Forest
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(x_test, y_test)

0.9796296296296296

#### Dari 3 pengujian di atas selalu berubah2 ketika di dilakukan cek enter lagi ketika pengecekan. kita biar tau akurasi sebenarnya dengan KFold


In [6]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [8]:
def get_score (model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [9]:
get_score(LogisticRegression(),X_train, x_test, y_train, y_test)

D:\New folder\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9629629629629629

In [10]:
get_score(SVC(),X_train, x_test, y_train, y_test)
# 2 hal ini akurasinya kecil

0.9925925925925926

In [11]:
# Pengujian dengan KFall, lebih baik dalam memisahkan lipatan dalam membagi klasifikasi
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [12]:
# ini Cara melihat KFold bekerja
score_1 = []
score_svm = []
score_rf = []

for train_index, test_index in kf.split(Digits.data):
    X_train, x_test, y_train, y_test = Digits.data[train_index], Digits.data[test_index], \
                                        Digits.target[train_index], Digits.target[test_index]
    
    score_1.append(get_score(LogisticRegression(), X_train, x_test, y_train, y_test))
    score_svm.append(get_score(SVC(), X_train, x_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, x_test, y_train, y_test))
    # memakai model di bawah ribet sekali, dalam membaca data
    #print(get_score(LogisticRegression(), x_train, x_test, y_train, y_test))
    #print(get_score(SVC(), x_train, x_test, y_train, y_test))
    #print(get_score(RandomForestClassifier(), x_train, x_test, y_train, y_test))

D:\New folder\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
D:\New folder\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warnin

In [13]:
score_1

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [14]:
score_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [15]:
score_rf

[0.9248747913188647, 0.9432387312186978, 0.9298831385642737]

#### Jadi di atas adalah hasil dari akurasi dari masing2 model
#### selanjutnya kita cek memakai metode escelon apa benar hasil di atas. dengan cross val score

In [16]:
from sklearn.model_selection import cross_val_score

In [17]:
cross_val_score(LogisticRegression(), Digits.data, Digits.target)

D:\New folder\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
D:\New folder\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warnin

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [18]:
cross_val_score(SVC(), Digits.data, Digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [19]:
cross_val_score(RandomForestClassifier(n_estimators=40), Digits.data, Digits.target)

array([0.94166667, 0.90555556, 0.95821727, 0.96657382, 0.9275766 ])