In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
Data = pd.read_csv('homeprices.csv')

In [3]:
Data.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
items = linear_model.LinearRegression()
items.fit(Data[['area']],Data.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [5]:
items.coef_

array([135.78767123])

In [6]:
items.intercept_

180616.43835616432

In [7]:
items.predict(np.array(3000).reshape(1, -1))

array([587979.45205479])

In [8]:
import pickle

In [9]:
with open('model_pickle','wb') as f:
    pickle.dump(items,f)

In [10]:
with open('model_pickle','rb') as f:
    mp = pickle.load(f)

In [11]:
mp.predict(np.array(3000).reshape(1, -1))

array([587979.45205479])

In [12]:
from sklearn.externals import joblib
joblib.dump(items,'model_joblib')

D:\New folder\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


['model_joblib']

In [13]:
mj = joblib.load('model_joblib')

In [14]:
mj.predict(np.array(3000).reshape(1, -1))

array([587979.45205479])

In [15]:
mj.coef_

array([135.78767123])

In [16]:
mj.intercept_

180616.43835616432